spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: servicio-productos
          uri: lb://servicio-productos
          predicates: 
            - Path=/api/productos/**
          filters:
            - StripPrefix=2  
            - EjemploCookie= Hola mi mensaje personalizado, usuario, AlejandroBravo
        - id: servicio-item
          uri: lb://servicio-item
          predicates: 
            - Path=/api/item/**
          filters:
            - StripPrefix=2     